### ISSUE TITLE
dependencies to workspace packages should be updated to actual version before publishing

### ISSUE THREAD

**Issue by TimoGlastra** [berendsliedrecht/sd-jwt-ts#12]
Now when installing `@sd-jwt/core` it will prompt you which version of the other `@sd-jwt` you want to install as it can't find a match for `workspace:*`

**Comment by berendsliedrecht** [comment]
Hmmm, pnpm should handle this... that's weird. Let me do some debugging.

**Comment by TimoGlastra** [comment]
Did some debugging on my end and it seems `release-it` is not compatible with pnpm workspaces. For pnpm to work `pnpm publish` and `pnpm pack` needs to be called rather than `npm publish` and `npm pack`.

There's some discussions and open PRs here:
- https://github.com/release-it-plugins/workspaces/pull/79
- https://github.com/release-it-plugins/workspaces/pull/110
But no support at the moment ( and we would need to add the workspaces plugin to release-it as well )

**Comment by TimoGlastra** [comment]
It might be wortwhile to look into pnpm publish with changesets. The changesets github action allows to create github release etc.. But it would introduce a new way to do changelog management, etc.. For now I think it might be easiest to use lerna, but only for the version and publishing part, not for the whole monorepo management part (pnpm does a good job of that).

That will give us similar behaviour to current one for now (with the issues addressed). PR incoming
